---

- name: Install OS X applications
  homebrew_cask:
    name: "{{ item }}"
    update_homebrew: yes
  with_items: "{{ homebrew_cask_applications }}"
  tags:
    - cask

- import_tasks: mas.yml
  tags:
    - mas
