---

- name: Updating homebrew and upgrading packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Adding additional taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Installing basic tools
  homebrew:
    name: "{{ item }}"
  with_items: "{{ basic_tools  }}"
  tags:
    - homebrew

- name: Installing cask applications
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ homebrew_cask_applications }}"
  tags:
    - cask

- import_tasks: python.yml
  tags:
    - python

- import_tasks: go.yml
  tags:
    - go

- import_tasks: node.yml
  tags:
    - node

- import_tasks: fish.yml
  tags:
    - fish

- import_tasks: vim.yml
  tags:
    - vim

- import_tasks: git.yml
  tags:
    - git

- import_tasks: keys.yml
  tags:
    - keys

- import_tasks: mas.yml
  tags:
    - mas

- import_tasks: osx.yml
  tags:
    - osx

