---

- name: Updating homebrew and upgrading packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  tags:
    - homebrew

- name: Installing cask applications
  homebrew_cask:
    name: "{{ item }}"
  with_items: "{{ homebrew_cask_applications }}"
  tags:
    - cask

- import_tasks: mas.yml
  tags:
    - mas

- name: Installing Python related packages
  homebrew:
    name: "{{ item }}"
  with_items: "{{ python_brew_packages }}"
  tags:
    - python

- import_tasks: node.yml
  tags:
    - node

- import_tasks: fish.yml
  tags:
    - fish

- import_tasks: vim.yml
  tags:
    - vim
