---

- name: Installing MAS
  homebrew:
    name: mas

# mas signin doesn't work in case you're wondering
- name: Checking MAS login status; Sign in using the App Store if this fails
  command: mas account
  changed_when: false

- name: Listing installed MAS apps
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensuring configured MAS apps are installed
  command: mas install {{ item.id }}
  with_items: "{{ mas_applications }}"
  when: item.id not in mas_list.stdout
