---

# Impossible to determine when any of these things change

# Section: General ->>1
# -------------------------------------------------------------------------
- name: Saving to disk instead of iCloud by default
  command: defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
  changed_when: false

- name: Disabling open application confirmation dialog
  command: defaults write com.apple.LaunchServices LSQuarantine -bool false
  changed_when: false

- name: Disabling autocorrect
  command: defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
  changed_when: false

- name: Disabling smart quotes substitution
  command: defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
  changed_when: false

- name: Disabling automatic capitalization
  command: defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
  changed_when: false

- name: Disabling smart dashes
  command: defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
  changed_when: false

- name: Disabling period substitution
  command: defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
  changed_when: false

- name: Enabling Dark interface
  command: defaults write NSGlobalDomain AppleInterfaceStyle Dark
  changed_when: false

- name: Showing battery percentage
  command: defaults write com.apple.menuextra.battery ShowPercent -string "YES"
  changed_when: false

# Section: I/O ->>1
# -------------------------------------------------------------------------
- name: Enabling tap to click
  shell: >
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 &&
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1 &&
    defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1 &&
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1
  changed_when: false

- name: Enabling three finger drag
  shell: >
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -bool true &&
    defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -bool true
  changed_when: false

- name: Enabling four finger horizontal swipe
  command: defaults write NSGlobalDomain com.apple.AppleMultitouchTrackpad.TrackpadFourFingerHorizSwipeGesture -int 2
  changed_when: false

- name: Using the all powerful metric system
  shell: >
    defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters" &&
    defaults write NSGlobalDomain AppleMetricUnits -bool true
  changed_when: false

- name: Requiring password immediately after sleep or screen saver begins
  shell: >
    defaults write com.apple.screensaver askForPassword -int 1 &&
    defaults write com.apple.screensaver askForPasswordDelay -int 0
  changed_when: false

# Section: Finder ->>1
# -------------------------------------------------------------------------
- name: Changing finder default folder to the user folder
  shell: >
    defaults write com.apple.finder NewWindowTarget -string "PfHm" &&
    defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/"
  changed_when: false

- name: Hiding tags in sidebar
  command: defaults write com.apple.finder ShowRecentTags -int 0
  changed_when: false

- name: Showing some stuff on Desktop
  shell: >
    defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -int 1 &&
    defaults write com.apple.finder ShowMountedServersOnDesktop -int 1 &&
    defaults write com.apple.finder ShowRemovableMediaOnDesktop -int 1
  changed_when: false

- name: Showing filename extensions
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true
  changed_when: false

- name: Searching on current folder
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
  changed_when: false

- name: Showing path bar
  command: defaults write com.apple.finder ShowPathbar -bool true
  changed_when: false

- name: Displaying full POSIX path as Finder window title
  command: defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
  changed_when: false

- name: Avoiding creating .DS_Store files on network or USB volumes
  shell: >
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true &&
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
  changed_when: false

- name: Showing Library folder
  command: chflags nohidden ~/Library
  changed_when: false

# Section: Dock ->>1
# -------------------------------------------------------------------------
- name: Enabling magnification
  command: defaults write com.apple.dock magnification -int 1
  changed_when: false

- name: Minimizing applications into its icon
  command: defaults write com.apple.dock "minimize-to-application" -int 1
  changed_when: false

- name: Changing dock size
  shell: >
    defaults write com.apple.dock largesize -int 79 &&
    defaults write com.apple.dock tilesize -int 48
  changed_when: false

# Section: Tweetbot ->>1
# -------------------------------------------------------------------------
- name: Bypassing t.co urls in Tweetbot
  command: defaults write com.tapbots.TweetbotMac OpenURLsDirectly -bool true
  changed_when: false

# Section: Spotlight
# -------------------------------------------------------------------------
- name: Disabling some spotlight search results
  shell: >
    defaults write com.apple.spotlight orderedItems -array \
      '{"enabled" = 1;"name" = "APPLICATIONS";}' \
      '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
      '{"enabled" = 1;"name" = "DIRECTORIES";}' \
      '{"enabled" = 1;"name" = "PDF";}' \
      '{"enabled" = 1;"name" = "MENU_CONVERSION";}' \
      '{"enabled" = 1;"name" = "MENU_EXPRESSION";}' \
      '{"enabled" = 1;"name" = "MENU_DEFINITION";}' \
      '{"enabled" = 1;"name" = "DOCUMENTS";}' \
      '{"enabled" = 1;"name" = "CONTACT";}' \
      '{"enabled" = 0;"name" = "MESSAGES";}' \
      '{"enabled" = 0;"name" = "EVENT_TODO";}' \
      '{"enabled" = 0;"name" = "IMAGES";}' \
      '{"enabled" = 0;"name" = "BOOKMARKS";}' \
      '{"enabled" = 0;"name" = "MUSIC";}' \
      '{"enabled" = 0;"name" = "FONTS";}' \
      '{"enabled" = 0;"name" = "MOVIES";}' \
      '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
      '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
      '{"enabled" = 0;"name" = "MENU_OTHER";}' \
      '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
  changed_when: false

- name: Disabling shared lookup suggestions
  command: defaults write com.apple.lookup.shared LookupSuggestionsDisabled -int 1
  changed_when: false

# Section: App Store ->>1
# -------------------------------------------------------------------------
- name: Checking for updates daily instead of weekly
  command: defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
  changed_when: false
